### ISSUE TITLE
Question: Could not parse rocks for plugins that have a git field?

### ISSUE THREAD

**Issue by xsh005** [nvim-neorocks/rocks-git.nvim#13]
![Screenshot from 2024-01-14 13-11-54](https://github.com/nvim-neorocks/rocks-git.nvim/assets/90909185/35a5102e-c1b3-44aa-9fc7-f4b09442858a)

rocks.toml:

```toml
# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# configuration related settings
[config]
prefix = "nano.config"

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.6.1" # rocks.nvim can also manage itself :D
"rocks-git.nvim" = "1.2.1"
"telescope.nvim" = { version = "scm", event = "UIEnter" }
nvim-dap = "0.7.0"
"haskell-tools.nvim" = "3.1.3"
nvim-treesitter = { version = "0.1", config = "treesitter" }

[plugins.comment]
git = "numToStr/Comment.nvim"
```

`plugins.comment` does indeed lack a version field, but I do have `rocks-git` installed... Not sure what's going on here. Sorry for bothering!
