### ISSUE TITLE
[error]: module 'toml_edit' not found on install

### ISSUE THREAD

**Issue by dmun** [nvim-neorocks/rocks-git.nvim#19]
Hi there! I tried to install rocks-git.nvim with `:Rocks install rocks-git.nvim` on macOS and got the following error.

Not sure if it's related to https://github.com/nvim-neorocks/rocks.nvim/issues/250 since it's my first time setting up rocks.nvim

## Error
```
Error detected while processing /Users/david/.local/share/nvim/rocks/lib/luarocks/rocks-5.1/rocks-git.nvim/1.3.1-1/plugin/rocks-git.lua:             
E5113: Error while calling lua chunk: ...share/nvim/rocks/share/lua/5.1/rocks/config/internal.lua:55: module 'toml_edit' not found:                  
        no field package.preload['toml_edit']                                                                                                        
        no file './toml_edit.lua'                                                                                                                    
        no file '/Users/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1/toml_edit.lua'                                                          
        no file '/usr/local/share/lua/5.1/toml_edit.lua'                                                                                             
        no file '/usr/local/share/lua/5.1/toml_edit/init.lua'                                                                                        
        no file '/Users/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/toml_edit.lua'                                                             
        no file '/Users/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/toml_edit/init.lua'                                                        
        no file '/Users/david/.local/share/nvim/rocks/share/lua/5.1/toml_edit.lua'                                                                   
        no file '/Users/david/.local/share/nvim/rocks/share/lua/5.1/toml_edit/init.lua'                                                              
        no file './toml_edit.so'                                                                                                                     
        no file '/usr/local/lib/lua/5.1/toml_edit.so'                                                                                                
        no file '/Users/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/toml_edit.so'                                                                
        no file '/usr/local/lib/lua/5.1/loadall.so'                                                                                                  
        no file '/Users/david/.local/share/nvim/rocks/lib/lua/5.1/toml_edit.dylib'                                                                   
        no file '/Users/david/.local/share/nvim/rocks/lib64/lua/5.1/toml_edit.dylib'                                                                 
stack traceback:                                                                                                                                     
        [C]: in function 'require'                                                                                                                   
        ...share/nvim/rocks/share/lua/5.1/rocks/config/internal.lua:55: in function 'get_rocks_toml'                                                 
        ...ocal/share/nvim/rocks/share/lua/5.1/rocks-git/config.lua:34: in main chunk                                                                
        [C]: in function 'require'                                                                                                                   
        ...ocal/share/nvim/rocks/share/lua/5.1/rocks-git/parser.lua:18: in main chunk                                                                
        [C]: in function 'require'                                                                                                                   
        .../.local/share/nvim/rocks/share/lua/5.1/rocks-git/git.lua:21: in main chunk                                                                
        [C]: in function 'require'                                                                                                                   
        .../share/nvim/rocks/share/lua/5.1/rocks-git/operations.lua:20: in main chunk                                                                
        [C]: in function 'require'                                                                                                                   
        ....local/share/nvim/rocks/share/lua/5.1/rocks-git/init.lua:37: in main chunk                                                                
        [C]: in function 'require'                                                                                                                   
        ...ks/rocks-5.1/rocks-git.nvim/1.3.1-1/plugin/rocks-git.lua:5: in main chunk                                                                 
Error detected while processing /Users/david/.local/share/nvim/rocks/lib/luarocks/rocks-5.1/rocks.nvim/2.21.0-1/plugin/rocks.lua:                    
Vim:E5113: Error while calling lua chunk: ...ks/rocks-5.1/rocks-git.nvim/1.3.1-1/plugin/rocks-git.lua:5: loop or previous error loading module 'rocks
-git'                                                                                                                                                
stack traceback:                                                                                                                                     
^I[C]: in function 'require'                                                                                                                         
^I...ks/rocks-5.1/rocks-git.nvim/1.3.1-1/plugin/rocks-git.lua:5: in main chunk                                                                       
^I[C]: at 0x0102911a80                                                                                                                               
^I[C]: in function 'pcall'                                                                                                                           
^I.../.local/share/nvim/rocks/share/lua/5.1/rocks/runtime.lua:71: in function 'source'                                                               
^I.../.local/share/nvim/rocks/share/lua/5.1/rocks/runtime.lua:83: in function 'source_plugin'                                                        
^I.../.local/share/nvim/rocks/share/lua/5.1/rocks/runtime.lua:150: in function 'packadd'                                                             
^I.../.local/share/nvim/rocks/share/lua/5.1/rocks/runtime.lua:176: in function 'source_start_plugins'                                                
^I.../luarocks/rocks-5.1/rocks.nvim/2.21.0-1/plugin/rocks.lua:68: in main chunk 

```

## rocks.toml
```toml
# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.21.0"
fzf-lua = "0.0.1216"
"rocks-config.nvim" = "1.3.1"
"neodev.nvim" = "2.5.2"
"gruvbox.nvim" = "2.0.0"
"oil.nvim" = "2.7.0"
"lualine.nvim" = "scm"
"mini.pairs" = "0.9.0"
"grapple.nvim" = "0.28.1"
"rocks-git.nvim" = "1.3.1"
# "nvim-colorizer.lua" = { git = "NvChad/nvim-colorizer.lua" }

[config]
plugins_dir = "plugins/"
auto_setup = false
colorscheme = "gruvbox"
```
