### ISSUE TITLE
`ignore_tags` option overwritten in `rocks.toml` after `:Rocks update`

### ISSUE THREAD

**Issue by sandersantema** [nvim-neorocks/rocks-git.nvim#71]
Using `rocks.nvim 2.40.5` and  `rocks-git.nvim 2.4.0` an entry such as the following:
``` toml
[plugins.nvim-origami]
git = "chrisgrieser/nvim-origami"
ignore_tags = true
opt = true
``` 

looks like the following after `:Rocks update`
``` toml
[plugins.nvim-origami]
git = "chrisgrieser/nvim-origami"
rev = "8487fd83b681caf1e91339fa763ae3d1ebcfcb96"
opt = true
``` 

My understanding of the `ignore_tags` option was that `:Rocks update` would always update packages with that option to the latest git revision, which is why I expect it to not be overwritten.

I'm fairly certain this is a bug having to do solely with the two packages mentioned, hence the sparsity of other information. I'm happy to provide more details if I assumed wrong.

**Comment by mrcjkb** [comment]
Hey 👋 

Thanks for reporting. Fixed in #72

**Comment by sandersantema** [comment]
With this change (and on the latest `rocks-git.nvim 2.5.0`) it now correctly leaves `ignore_tags` but also writes back the `rev`, i.e. 
```toml
[plugins.vim-endwise]
git = "tpope/vim-endwise"
ignore_tags = true
```
becomes
```toml
[plugins.vim-endwise]
git = "tpope/vim-endwise"
rev = "3719ffddb5e42bf67b55b2183d7a6fb8d3e5a2b8"
ignore_tags = true
```

Is this intended behavior?
